blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from blog_app.views import ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleCreateView, ArticleSignUpView, ArticleDeleteView, DeployWebhookView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog_app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/new/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_update'),
    path('signup/', ArticleSignUpView.as_view(), name='signup'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('webhook/', DeployWebhookView.as_view(), name='deploy_webhook'),



# not used in production, just to serve static files

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),  # Include blog_app's URLs with its namespace
    path('accounts/', include('django.contrib.auth.urls')),
    path('markdownx/', include('markdownx.urls')),
]

blog_app/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class UserProfile(models.Model):

    USER = 0
    ADMIN = 1
    ROLE_CHOICES = [
        (USER, 'User'),
        (ADMIN, 'Admin'),
    ]
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # a user is able to have not authored an article have
    authored = models.ManyToManyField('Article', through='AuthoredThrough', blank=True)
    role = models.IntegerField(default=USER, choices=ROLE_CHOICES)

    def __str__(self):
        return self.user.username


class Article(models.Model):
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(4, "Title must be greater than 4 characters")],
    )
    body = MarkdownxField(null=True)
    authors = models.ManyToManyField('UserProfile', through='AuthoredThrough', blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Convert the body to HTML when rendering
    def formatted_markdown(self):
        return markdownify(self.body)
    def __str__(self):
        return self.title


# Through Table to handle the Many-To-Many relationship
class AuthoredThrough(models.Model):
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

blog_app/views.py
import os
import logging
import subprocess

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Article, UserProfile, AuthoredThrough
from django.http import HttpResponseForbidden
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.utils.decorators import method_decorator

from .utilities import RoleRequiredMixin

class ArticleListView(ListView):
    model = Article
    template_name = 'blog_app/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        # Order by published_date in descending order (most recent first)
        # and limit the number of results to 3
        return Article.objects.order_by('-created_at')[:3]

    # adding the additional context from Userprofile model that is needed to show/hide the "create" button
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            user_profile = UserProfile.objects.get(user=self.request.user)
            context['user_role'] = user_profile.role
        else:
            context['user_role'] = None

        context['ADMIN_ROLE'] = UserProfile.ADMIN

        return context



class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog_app/article_detail.html'
    context_object_name = 'article'

    # adding the additional context from Userprofile model that is needed to show/hide the "update" button
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            user_profile = UserProfile.objects.get(user=self.request.user)
            context['user_role'] = user_profile.role
        else:
            context['user_role'] = None

        context['ADMIN_ROLE'] = UserProfile.ADMIN

        return context


class ArticleCreateView(RoleRequiredMixin, LoginRequiredMixin, CreateView):
    required_role = UserProfile.ADMIN
    model = Article
    fields = ["title", "body"]
    template_name = 'blog_app/article_create.html'

    def get_success_url(self):
        return reverse_lazy('blog_app:article_detail', kwargs={'pk': self.object.pk})

    # saving user to the database automatically
    def form_valid(self, form):
        # Save the article first to get the instance
        response = super().form_valid(form)

        # Add the current user as an author of the article
        authored = AuthoredThrough(author=self.request.user.userprofile, article=self.object)
        authored.save()

        return response  # to ensure get_success_url() works as intended


class ArticleUpdateView(RoleRequiredMixin, LoginRequiredMixin, UpdateView):
    required_role = UserProfile.ADMIN
    model = Article
    fields = ["title", "body"]
    template_name = 'blog_app/article_update.html'

    # to protect data from non-admins on a database_level
    def get_queryset(self):
        if self.request.user.userprofile.role == UserProfile.USER:
            return HttpResponseForbidden("This page is only accessible for admins.")
        return super().get_queryset()

    def get_success_url(self):
        return reverse_lazy('blog_app:article_detail', kwargs={'pk': self.object.pk})

    # saving user to the database automatically, if not duplicate
    def form_valid(self, form):
        # Save the article first to get the instance
        response = super().form_valid(form)
        # Check if the author-article relationship already exists, if it doesn't add it
        authored_exists = AuthoredThrough.objects.filter(
            author=self.request.user.userprofile,
            article=self.object
        ).exists()

        if not authored_exists:
            authored = AuthoredThrough(author=self.request.user.userprofile, article=self.object)
            authored.save()

        return response  # to ensure get_success_url works as intended


class ArticleSignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')  # Redirect to login page after successful sign-up


class ArticleDeleteView(RoleRequiredMixin, DeleteView):
    required_role = UserProfile.ADMIN
    model = Article
    template_name = 'blog_app/article_confirm_delete.html'
    success_url = reverse_lazy('blog_app:article_list')


logger = logging.getLogger(__name__)


@method_decorator(csrf_exempt, name='dispatch')
class DeployWebhookView(View):
    def post(self, request, *args, **kwargs):
        script_path = '/home/PouriaMoradpour/BlogWebsite/deploy.sh'

        if os.path.exists(script_path):
            logger.info(f'Script exists at {script_path}. Running the script.')
            try:
                subprocess.run([script_path], check=True)
            except subprocess.CalledProcessError as e:
                logger.error(f'Error running the script: {e}')
                return HttpResponse(f'Script execution failed: {e}', status=500)
        else:
            logger.error(f'Script not found at {script_path}')
            return HttpResponse(f'Script not found at {script_path}', status=404)

        return HttpResponse('Deployment triggered')

    def get(self, request, *args, **kwargs):
        return HttpResponse('Not allowed', status=405)

blog_app/templates/blog_app/article_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Article</title>
</head>
<body>
    <h1>Delete Article</h1>
    <p>Are you sure you want to delete article "{{ object.title }} (<a href="{% url 'blog_app:article_detail' object.pk %}">Cancel</a>)"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
        <a href="{% url 'blog_app:article_detail' object.pk %}">Cancel</a>
    </form>
</body>
</html>

blog_app/templates/blog_app/article_create.html
{% extends "blog_app/create_update_base.html" %}

{% block title %} Add an Article {% endblock %}
{% block content %}
    <h1>Adding an Article</h1>
{% endblock %}

blog_app/templates/blog_app/article_detail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{{ article.title }}</title>

      <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- font awesome -->
    <script src="https://kit.fontawesome.com/032ea820f5.js" crossorigin="anonymous"></script>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

    <!-- custom CSS for overriding Materialize -->
   <link rel="stylesheet" href="{% static 'blog_app/css/layout.css' %}">
   <link rel="stylesheet" href="{% static 'blog_app/css/article-detail.css' %}">

</head>
<body>

    <!-- navbar -->

  <div class="navbar-fixed">
    <nav class="nav-wrapper grey darken-4">
      <div class="container">
        <a href="{% url 'blog_app:article_list' %}" class="brand-logo">
            <img src="{% static 'blog_app/images/name.png' %}" alt="" class="responsive-img">
        </a>
        <a href="#" class="sidenav-trigger waves-effect waves-light" data-target="mobile-links">
          <i class="fa-solid fa-bars fa-xl teal-text" ></i>
        </a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'blog_app:article_list' %}#contact-me " class="teal-text text-accent-2 waves-effect waves-light">Contact</a></li>
          <li><a href="{% url 'blog_app:article_list' %}#about-me" class="teal-text text-accent-2 waves-effect waves-light">About Me</a></li>


              {% if user.is_authenticated %}
            <li class="teal-text ">

                  Logged in as
                  <span class="amber-text text-darken-2">{{user.username}}</span>
            </li>

            <li>
                  <a href="{% url 'logout' %}?next={{ request.path }}" class="teal-text text-accent-2 tooltipped waves-effect waves-light" data-position="bottom" data-tooltip="Log Out">
                      <i class="fa-solid fa-right-from-bracket fa-xl teal-text" ></i>
                  </a>
            </li>

              {% else %}
            <li>
              <a href="{% url 'login' %}?next={{ request.path }}"
                 class="btn teal lighten-2 grey-text text-darken-4 waves-effect waves-light">
                  <i class="fa-solid fa-right-to-bracket fa-xl amber-text text-accent-2" ></i>
                  Login
              </a>
            </li>

             <li>
              <a href="{% url 'blog_app:signup' %}?next={{ request.path }}"
                 class=" teal-text waves-effect waves-light">
                  <i class="fa-solid fa-user-plus fa-xl amber-text text-accent-2" ></i>
                  Sign Up
              </a>
            </li>

              {% endif %}

        </ul>
      </div>
    </nav>
  </div>

  <!-- sidebar -->
  <ul class="sidenav grey darken-4" id="mobile-links">
      <li><a href="{% url 'blog_app:article_list' %}#contact-me" class="teal-text text-accent-2 waves-effect waves-light">Contact</a></li>
      <li><a href="{% url 'blog_app:article_list' %}#about-me" class="teal-text text-accent-2 waves-effect waves-light">About Me</a></li>
      <li>
          {% if user.is_authenticated %}
            <li class="teal-text">
              <div class="container">
              Logged in as
              <span class="amber-text text-darken-2"> {{user.username}}
                <a href="{% url 'logout' %}?next={{ request.path }}" class="teal-text text-accent-2 tooltipped waves-effect waves-light" data-position="bottom" data-tooltip="Log Out">
                    <i class="fa-solid fa-right-from-bracket fa-xl teal-text" ></i>
                </a>
              </span>
                  </div>

            </li>

              {% else %}
            <li>
              <a href="{% url 'login' %}?next={{ request.path }}"
                 class="btn teal lighten-2 grey-text text-darken-4 waves-effect waves-light">
                  <i class="fa-solid fa-right-to-bracket fa-xl amber-text text-accent-2" ></i>
                  Login
              </a>
            </li>

            <li>
              <a href="{% url 'blog_app:signup' %}?next={{ request.path }}"
                 class=" teal-text waves-effect waves-light">
                  <i class="fa-solid fa-user-plus fa-xl amber-text text-accent-2" ></i>
                  Sign Up
              </a>
            </li>
          {% endif %}


  </ul>

<div class="container">

    <h2 class="teal-text text-accent-2">
        {{ article.title }}
    </h2>

    <h6 class="teal-text text-darken-2" style="font-size: 0.9em">
        by
        {% for author in article.authors.all %}
            <span class="amber-text text-accent-3">{{ author.user.username }}</span>{% if not forloop.last %} {% endif %}
        {% endfor %} - Published on <span class="teal-text text-accent-4">{{ article.created_at }}</span>
        {% if article.updated_at != article.created_at %}
          (updated on <span class="teal-text text-accent-4">{{ article.updated_at }}</span>)
        {% endif %}
    </h6>

     <div class="fixed-action-btn">
        <a href="{% url 'blog_app:article_list' %}" class="btn-floating btn-large">
            <i class="fa-solid fa-house amber darken-3 teal-text text-darken-2"></i>
        </a>
     </div>

    <div class="better-p flow-text overlay vertical-adjust-body">
    <p>
         {{ article.formatted_markdown|safe }}
    </p>
    </div>

</div>



{% if user_role == ADMIN_ROLE %}
<a href="{% url 'blog_app:article_update' pk=article.pk %}">Edit Article</a>
    <a href="{% url 'blog_app:article_delete' article.pk %}">Delete Article</a>

{%endif%}

{% include 'blog_app/footer.html' %}

  <!-- jQuery for adding logic to elements -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  <script src="{% static 'blog_app/js/base.js' %}"></script>

</body>
</html>

blog_app/templates/blog_app/article_list.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <title>Pouria's Blog</title>
<!-- importing Materialize, Font Awsome -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- font awesome -->
    <script src="https://kit.fontawesome.com/032ea820f5.js" crossorigin="anonymous"></script>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

    <!-- custom CSS for overriding Materialize -->
   <link rel="stylesheet" href="{% static 'blog_app/css/article-list.css' %}">
   <link rel="stylesheet" href="{% static 'blog_app/css/layout.css' %}">
   <link rel="stylesheet" href="{% static 'blog_app/css/background.css' %}">

</head>

<!-- navbar -->
<body>
  <div class="navbar-fixed">
    <nav class="nav-wrapper grey darken-4">
      <div class="container">
        <a href="#" class="brand-logo">
            <img src="{% static 'blog_app/images/name.png' %}" alt="" class="responsive-img">
        </a>
        <a href="#" class="sidenav-trigger waves-effect waves-light" data-target="mobile-links">
          <i class="fa-solid fa-bars fa-xl teal-text" ></i>
        </a>
        <ul class="right hide-on-med-and-down">
          <li><a href="#contact-me " class="teal-text text-accent-2 waves-effect waves-light">Contact</a></li>
          <li><a href="#about-me" class="teal-text text-accent-2 waves-effect waves-light">About Me</a></li>


              {% if user.is_authenticated %}
            <li class="teal-text ">

                  Logged in as
                  <span class="amber-text text-darken-2">{{user.username}}</span>
            </li>

            <li>
                  <a href="{% url 'logout' %}?next={{ request.path }}" class="teal-text text-accent-2 tooltipped waves-effect waves-light" data-position="bottom" data-tooltip="Log Out">
                      <i class="fa-solid fa-right-from-bracket fa-xl teal-text" ></i>
                  </a>
            </li>

              {% else %}
            <li>
              <a href="{% url 'login' %}?next={{ request.path }}"
                 class="btn teal lighten-2 grey-text text-darken-4 waves-effect waves-light">
                  <i class="fa-solid fa-right-to-bracket fa-xl amber-text text-accent-2" ></i>
                  Login
              </a>
            </li>

             <li>
              <a href="{% url 'blog_app:signup' %}?next={{ request.path }}"
                 class=" teal-text waves-effect waves-light">
                  <i class="fa-solid fa-user-plus fa-sm amber-text text-accent-2" ></i>
                  Sign Up
              </a>
            </li>
              {% endif %}

        </ul>
      </div>
    </nav>
  </div>

  <!-- sidebar -->
  <ul class="sidenav grey darken-4" id="mobile-links">
      <li><a href="#contact-me" class="teal-text text-accent-2 waves-effect waves-light">Contact</a></li>
      <li><a href="#about-me" class="teal-text text-accent-2 waves-effect waves-light">About Me</a></li>
      <li>
          {% if user.is_authenticated %}
            <li class="teal-text">
              <div class="container">
              Logged in as
              <span class="amber-text text-darken-2"> {{user.username}}
                <a href="{% url 'logout' %}?next={{ request.path }}" class="teal-text text-accent-2 tooltipped waves-effect waves-light" data-position="bottom" data-tooltip="Log Out">
                    <i class="fa-solid fa-right-from-bracket fa-xl teal-text" ></i>
                </a>
              </span>
                  </div>

            </li>

              {% else %}
            <li>
              <a href="{% url 'login' %}?next={{ request.path }}"
                 class="btn teal lighten-2 grey-text text-darken-4 waves-effect waves-light">
                  <i class="fa-solid fa-right-to-bracket fa-xl amber-text text-accent-2" ></i>
                  Login
              </a>
            </li>

            <li>
              <a href="{% url 'blog_app:signup' %}?next={{ request.path }}"
                 class=" teal-text waves-effect waves-light">
                  <i class="fa-solid fa-user-plus fa-xl amber-text text-accent-2" ></i>
                  Sign Up
              </a>
            </li>
          {% endif %}

  </ul>

    <!-- article cards -->
    <div class="container">
    <div class="row">
        <div class="col s12 l12">
            <h2 class="teal-text text-accent-2 center-align">Blog <span class="amber-text text-lighten-1">Posts</span></h2>
            <h6 class="teal-text text-darken-2 center-align">I would be really happy if you read these :)</h6>
        </div>

     {% for article in articles %}
      <div class="col s12 l4">
        <div class="card grey darken-4" style="border-radius: 15px;">
          <div class="card-content">
            <span class="card-title amber-text text-lighten-1">{{ article.title }}</span>
            <div class="multi-line-truncate teal-text text-lighten-1">
                <p>{{ article.formatted_markdown|safe }}</p>
            </div>
            <span class="grey-text">by {% for author in article.authors.all %}
                {{ author.user.username }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </span>
          </div>
          <div class="card-action" style="border-radius: 0 0 15px 15px;">
            <a href="{% url 'blog_app:article_detail' article.id %}" class="teal-text text-accent-2 waves-effect waves-light"><strong class="amber-text text-lighten-1"> Read</strong> The Blogpost</a>
          </div>
        </div>
      </div>

        {% empty %}
        <p>No articles available.</p>
       {% endfor %}
    </div>
    </div>

    <!-- about me -->
  <div class="container">
      <div class="row">
          <div class="col l7 s12">
              <h3 class="teal-text text-accent-2 scrollspy" id="about-me">About<span class="amber-text text-lighten-1 "> Me</span></h3>
              <div class="text-overlay">
                  <strong class="teal-text text-lighten-2 left-align"  >
                    Hey there!
                    I am interested in computer science, mathematics, and programming. I love developing creative ideas with code and working on various projects that reflect these interests. Indeed, there is nothing quite like satisfaction if something you have been building opens its eyes.

                    Although I am currently an undergraduate student in Computer Science at the University of Isfahan, my self-motivation and curiosity drive me to learn continuously. I always get excited about entering a new frontier and learning new skills. Currently, as a student, I am focusing on learning and growing, but when it comes to your cool job offerings and internships that rhyme with my interests, I will most definitely consider working on them.

                    Proficient in English, actively learning German, and fluent in Persian, I enjoy connecting with people across the world and collaborating on innovative ideas. <span class="amber-text text-lighten-1">Thanks for stopping by my site—I look forward to connecting!</span>
                  </strong>
              </div>
          </div>
          <div class="col push-l1 l3 vertical-adjust-img hide-on-med-and-down">
              <img src="{% static 'blog_app/images/me.jpg' %}" alt="Custom Image" class="circle responsive-img">
          </div>
      </div>
  </div>

  <!-- contact me -->
  <div class="container">
      <div class="row">
          <div class="col l8 s12" style="margin-top: 5em;">
              <h4 class="teal-text text-accent-2 align-right"> Let's <span class="amber-text text-lighten-1"> Build </span> Something Great <span class="amber-text text-lighten-1">Together</span>! </h4>
          </div>

          <div class="col l3 s12">
              <div class="text-overlay">
                  <h5 class="teal-text text-accent-2 scrollspy " id="contact-me" >Contact <span class="amber-text text-lighten-1">Me</span>!</h5>
                      <ul>
                          <li class="vertical-adjust-icon">
                              <a class="teal-text text-accent-2 tooltipped waves-effect waves-light" data-position="left" data-tooltip="pouriapmd83@gmail.com" href="mailto:https://pouriapmd83@gmail.com"><i class="fa-regular fa-envelope fa-xl amber-text text-lighten-1" ></i> Mail</a>
                          </li>

                          <li class="vertical-adjust-icon">
                              <a class="teal-text text-accent-2 tooltipped waves-effect waves-light"  data-position="left" data-tooltip="@Wunschsohn" href="https://t.me/Wunschsohn"><i class="fa-brands fa-telegram fa-xl amber-text text-lighten-1"></i> Telegram</a>
                          </li>

                          <li class="vertical-adjust-icon">
                              <a class="teal-text text-accent-2 tooltipped waves-effect waves-light"  data-position="left" data-tooltip="@simply-pouria" href="https://github.com/simply-pouria"><i class="fa-brands fa-github fa-xl amber-text text-lighten-1"></i> GitHub</a>
                          </li>

                          <li class="vertical-adjust-icon">
                              <a class="teal-text text-accent-2 tooltipped waves-effect waves-light"  data-position="left" data-tooltip="@PouriaMoradpour" href="https://x.com/PouriaMoradpour"><i class="fa-brands fa-x-twitter fa-xl amber-text text-lighten-1"></i> X</a>
                          </li>

                          <li class="vertical-adjust-icon">
                              <a class="teal-text text-accent-2 tooltipped waves-effect waves-light" data-position="left" data-tooltip="Pouria Moradpour" href="https://www.linkedin.com/in/pouria-moradpour-005b31284/"><i class="fa-brands fa-linkedin fa-xl amber-text text-lighten-1"></i> LinkedIn</a>
                          </li>


                      </ul>
              </div>
          </div>

          </div>
      </div>



{% if user_role == ADMIN_ROLE %}
<a href="{% url 'blog_app:article_create' %}">Add an Article!</a>
{%endif%}

{% include 'blog_app/footer.html' %}

  <!-- jQuery for adding logic to elements -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  <script src="{% static 'blog_app/js/base.js' %}"></script>

</body>

</html>

blog_app/templates/blog_app/article_update.html
{% extends "blog_app/create_update_base.html" %}

{% block title %} Update {{  object.title }} {% endblock %}


{% block content %}
    <h1>Updating {{object.title}}</h1>
{% endblock %}

blog_app/templates/blog_app/create_update_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Add or Edit{% endblock %}</title>
</head>
<body>
    {% block content %}
    <h1>Writing/Editing an Article</h1>
    {% endblock %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

blog_app/templates/blog_app/footer.html
{% load static %}

 <head>
       <link rel="stylesheet" href="{% static 'blog_app/css/footer.css' %}">
 </head>

<footer>
    <p>Made with <i class="fa-solid fa-heart fa-beat" style="color: #ff0000;"></i> by Pouria Moradpour</p>
    <a href="https://github.com/simply-pouria/BlogWebsite">This website is open source here</a>
</footer>

blog_app/templates/blog_app/login_status.html
    {% if user.is_authenticated %}
    <p>
        you're logged in as {{user.username}}
        <a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
    </p>
    {% else %}
    <p>
        you're not logged in
        <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
        don't have an account yet?
        <a href="{% url 'blog_app:signup' %}">Sign Up</a>

    </p>
    {% endif %}

templates/registeration/login.html
<html>
<head>
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>